### PR TITLE
Logger refactoring

### PR DESCRIPTION
**Pull request by Mikearaya**
testing/exploring new structure

### CODE REVIEW

**Comment by schmidsi** [comment]
I also did some typings of core-logger: https://github.com/unchainedshop/unchained/pull/289/commits/8cded0217ff6160599d7c19bd544691e7ad1f063 But it seems like you are making it more sophisticated than my minimalism. Maybe it helps anyways ;)

**Comment by Mikearaya** [comment]
yeah, just testing the water :)

**Comment by pozylon** [comment]
@Mikearaya I just rebased this branch on master and was wondering if we can complete this task

**Comment by Mikearaya** [comment]
@pozylon ok, I will start working on it

**Comment by pozylon** [comment]
In @joelmeiller s refactoring, most of the changes have been integrated partly, So I guess @joelmeiller look at the changes of this PR and include what makes sense

**Pull request closed without merging**
