### PR TITLE
Remove not found error

### PR DESCRIPTION
**Pull request by Mikearaya**
i've left `PaymentProviderNotFoundError` from `query.signPaymentProviderForCredentialRegistration` because it's almost a mutation and returning null might not be enough. plus anyone who calls this endpoint should be expected to provide a correct `paymentProviderId`.

### CODE REVIEW

**Comment by pozylon** [comment]
Great! Maybe that's a sign we have to change it to Mutation.signPaymentProvider... what do you think ? It sure invokes side-effects

**Comment by Mikearaya** [comment]
Yes but how big is the impact of this breaking change and should we introduce it now?

**Review by pozylon — APPROVED** [review]
I leave that up to you, code looks good for merge

**Comment by Mikearaya** [comment]
so far weng and publicare are not using it so I've decided to change it to a mutation. it would be great if you can confirm veloplus and others.
I'm merging this

**Pull request merged**
