### PR TITLE
Remove meta resolver

### PR DESCRIPTION
**Pull request by Mikearaya**
each payment provider should implement a type for PaymentCredential meta to be removed DataTrans, Strip, etc... because each expect different fields

### CODE REVIEW

**Comment by pozylon** [comment]
Documentation looks very good and else the changes are fine, which cases where we have arbitrary payload data that we have to generally make available to the frontend, still exist now? @Mikearaya

**Comment by Mikearaya** [comment]
@pozylon yes, projects need to define their own explicit resolvers now and no meta field will be available for the listed types. meta will be available at a resolver definition point

**Comment by Mikearaya** [comment]
anything you think should be added to this?

**Comment by Mikearaya** [comment]
@pozylon

**Comment by pozylon** [comment]
Meta Usage Today by the big shops:
- Order.meta
- Assortment.meta
- OrderDelivery.meta

**Comment by pozylon** [comment]
I fixed some things with controlpanel and removed the order meta props, tests all running through

**Review by pozylon — APPROVED** [review]

**Pull request merged**
