### PR TITLE
Add order sort

### PR DESCRIPTION
**Pull request by Mikearaya**
Adds
- orders sort
- `user.orders`, `user.quotations` & `user.enrollments` sort and queryString filters

related with #217

### CODE REVIEW

**Comment by Mikearaya** [comment]
@pozylon

**Comment by pozylon** [comment]
CI says it's not good yet @Mikearaya, please rebase on master (passes atm) and check out tests

**Comment by Mikearaya** [comment]
@pozylon tests are passing locally but i don't know why it's hanging in CI

**Comment by Mikearaya** [comment]
@pozylon i have used wrong import from meteor instead of uncainedshop :zany_face: , it is now ready

**Comment by pozylon** [comment]
@Mikearaya please check my comments in the review

**Comment by Mikearaya** [comment]
@pozylon what comment?

**Review by pozylon — CHANGES_REQUESTED** [review]

**Comment by pozylon** [comment]
@Mikearaya sorry i didn't submit the review I've been doing weeks ago 😆

**Comment by Mikearaya** [comment]
@pozylon resolved

**Pull request merged**
