### PR TITLE
feat: allow to update configuration of a cart item

### PR DESCRIPTION
**Pull request by macrozone**

### CODE REVIEW

**Comment by macrozone** [comment]
fixes https://github.com/unchainedshop/unchained/issues/43

**Comment by pozylon** [comment]
I guess we can remove updateCartItemQuantity then

**Comment by macrozone** [comment]
> I guess we can remove updateCartItemQuantity then

let's deprecated it first

**Comment by pozylon** [comment]
Looks good to me, I will merge this once the @deprectated is behind the updateCartItemQuantity.
https://www.apollographql.com/docs/apollo-server/features/directives.html

**Comment by macrozone** [comment]
can you do that? i have to juggle with 100erds of branches here and can't switch between them easily

**Comment by pozylon** [comment]
Done.

**Pull request merged**
