### PR TITLE
Themable CP

### PR DESCRIPTION
**Pull request by pozylon**

### CODE REVIEW

**Comment by pozylon** [comment]
With this branch, CP can be themed by following https://semantic-ui.com/usage/theming.html

**Review by schmidsi — APPROVED** [review]

**Comment by schmidsi** [comment]
So this chance allows us to theme the CP globally, but not per customer, right?

**Comment by pozylon** [comment]
Yeah, just globally, but a customer could copy the controlpanel folder over to his project and have it themed

**Comment by pozylon** [comment]
Das sind alli global variables womer cha setzä:

https://github.com/Semantic-Org/example-github/blob/master/semantic/src/themes/default/globals/site.variables

**Pull request merged**
